# Generated by Django 3.2.2 on 2023-05-18 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Мед. организация',
                'verbose_name_plural': 'Мед. организации',
                'db_table': 'med_organization',
            },
        ),
        migrations.CreateModel(
            name='MedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.IntegerField(choices=[(1, 'Админ'), (2, 'Глав. врач'), (3, 'Доктор'), (4, 'Пациент')], verbose_name='Роль')),
                ('med_organiizaciya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medorganization', verbose_name='Медицинская организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='polzovatel', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'med_user',
            },
        ),
    ]
