# Generated by Django 3.2.2 on 2023-05-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meduser',
            name='med_organiizaciya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.medorganization', verbose_name='Медицинская организация'),
        ),
    ]
