# Generated by Django 3.2.2 on 2023-05-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230525_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.DateField(blank=True, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='patient',
            name='polis',
            field=models.DateField(blank=True, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='patient',
            name='snils',
            field=models.DateField(blank=True, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='patientvariant',
            name='source_passport',
            field=models.DateField(blank=True, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='patientvariant',
            name='source_phone',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='patientvariant',
            name='source_polis',
            field=models.DateField(blank=True, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='patientvariant',
            name='source_snils',
            field=models.DateField(blank=True, null=True, verbose_name='СНИЛС'),
        ),
        migrations.CreateModel(
            name='RecomendationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment', verbose_name='Назначение')),
                ('mkb10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mkb10', verbose_name='МКБ10')),
            ],
            options={
                'verbose_name': 'Рекомендации по назначению',
                'verbose_name_plural': 'Рекомендации по назначению',
                'db_table': 'recomendation_assignment',
            },
        ),
    ]
