# Generated by Django 3.2.2 on 2023-05-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_patientvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allassignment',
            old_name='med_data_set',
            new_name='med_data_set_detail',
        ),
    ]
