# Generated by Django 3.2.2 on 2023-05-27 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_med_data_set_allassignment_med_data_set_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meddataset',
            name='import_status',
            field=models.IntegerField(choices=[(1, 'Успешный импорт'), (2, 'Не все записи импортированы'), (3, 'Ошибка чтения файла или файл не является Excel'), (4, 'Ошибка структуры файла или запроса'), (5, 'Ошибка заполнения обязательных полей')], verbose_name='Статус импорта'),
        ),
        migrations.AlterField(
            model_name='meddataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь кто импортировал'),
        ),
    ]
