# Generated by Django 3.2.2 on 2023-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230527_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meddataset',
            name='excel_in',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='excel на входе'),
        ),
        migrations.AlterField(
            model_name='meddataset',
            name='excel_out',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='excel с ошибками на выходе'),
        ),
        migrations.AlterField(
            model_name='meddataset',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Набор отправлен в архив'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
