# Generated by Django 3.2.2 on 2023-05-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230528_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='polis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='snils',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СНИЛС'),
        ),
    ]
