# Generated by Django 3.2.2 on 2023-05-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230528_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvariant',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Доктор/врач(родительская запись в БД)'),
        ),
    ]
