# Generated by Django 3.2.2 on 2023-05-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230528_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentvariant',
            name='source',
            field=models.IntegerField(choices=[(1, 'МИС Москвы')], default=1, verbose_name='Источник данных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentvariant',
            name='assignment',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignment', verbose_name='Назначение(родительская запись в БД)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспорт'),
        ),
    ]
