# Generated by Django 3.2.2 on 2023-05-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230528_1943'),
        ('api', '0012_auto_20230528_2017'),
    ]

    operations = [
    ]
