# Generated by Django 3.2.2 on 2023-05-29 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0008_auto_20230528_1943_0012_auto_20230528_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassignment',
            name='assignment_status',
            field=models.IntegerField(choices=[(1, 'Допустимое назначение'), (2, 'Недопустимое назначение'), (3, 'У МКБ10 нет рекомендаций')], verbose_name='Статус правильности назначения'),
        ),
        migrations.AlterField(
            model_name='assignmentindataset',
            name='assignment_status',
            field=models.IntegerField(choices=[(1, 'Допустимое назначение'), (2, 'Недопустимое назначение'), (3, 'У МКБ10 нет рекомендаций')], verbose_name='Статус правильности назначения'),
        ),
        migrations.AlterField(
            model_name='meddataset',
            name='import_status',
            field=models.IntegerField(choices=[(1, 'Успешный импорт'), (2, 'Не все записи импортированы'), (3, 'Ошибка чтения файла'), (4, 'Ошибка структуры файла или запроса'), (5, 'Ошибка прав доступа'), (6, 'Ошибка заполнения обязательных полей')], verbose_name='Статус импорта'),
        ),
        migrations.AlterField(
            model_name='meddatasetdetail',
            name='mkb10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mkb10', verbose_name='Диагноз МКБ 10'),
        ),
    ]
